---
title: "git_01"
author: "Flora Soto"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
How doth the little crocodile   
     Improve his shining tail,   
And pour the waters of the Nile   
     On every golden scale!   
    
How cheerfully he seems to grin,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
The city had withdrawn into itself  
And left at last the country to the country;  
When between whirls of snow not come to lie  
And whirls of foliage not yet laid, there drove  
A stranger to our yard, who looked the city,  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
        
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
My long two-pointed ladder's sticking through a tree  
Toward heaven still,  
And there's a barrel that I didn't fill  
Beside it, and there may be two or three  
Apples I didn't pick upon some bough.  
But I am done with apple-picking now.  
Essence of winter sleep is on the night,  
The scent of apples: I am drowsing off.  
I cannot rub the strangeness from my sight  
I got from looking through a pane of glass  
I skimmed this morning from the drinking trough  
And held against the world of hoary grass.  
It melted, and I let it fall and break.  
But I was well  
